name: Deploy Frontend no S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurando AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy no S3
        run: |
          aws s3 sync . s3://lab-waycarbon --delete --exclude ".*/*" --exclude "README.md"
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV
